sudo: required
services:
  - docker

before_install:
  - docker build -t idhruven/docker-react -f Dockerfile.dev .

script:
  - docker run idhruven/docker-react npm run test -- --coverage --bail

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-19287467319873"
  bucket_path: "docker-react" #AppName
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"